### PR TITLE
Свириденков Михаил, 2536

### PR DESCRIPTION
**Pull request by MSviridenkov**

### CODE REVIEW

**Comment by svasilinets** [comment]
There is no Service, which was minimal requirement.
0.

**Comment by MSviridenkov** [comment]
What about ScheduledExecutorService?

**Comment by svasilinets** [comment]
ExecutorService doesn't implement/extend an interface/class named "Service".

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/concurrent/ExecutorService.java#ExecutorService

**Comment by thevery** [comment]
You must use android.app.Service

**Pull request closed without merging**
